### ISSUE TITLE
이걸 global 객체로 쓰셔서 문제가 생깁니다

### ISSUE THREAD

**Issue by ezaurum** [ssoyyoung/GoDirectory#1]
https://github.com/ssoyyoung/GoDirectory/blob/918991703d0488a5c05cac4826bace6d9504e8da/mongo/crud/crud.go#L63

펑션 안에서 새로 생성해 주셔야 해요

**Comment by ezaurum** [comment]
global 로 쓰면 여러 함수에서 같이 쓰니까 문제가 생깁니다.

**Comment by ezaurum** [comment]
여러 객체에서 사용하고 싶으시다면 go루틴과 채널을 이용해서 공유해 주세요~ 오늘 나온 키 밸류 스토어를 고루틴과 채널을 사용해서 확장하시면 될 거 같네요 ㅎ

**Comment by ssoyyoung** [comment]
넵! 감사합니다ㅎㅎㅎ👍
